global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "./rules/alert-rules.yml"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'dcgm_exporter'
    static_configs:
      - targets: ['dcgm_exporter:9400']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']