services:
  alpine-ftp-server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - 21000-21010:21000-21010
    environment:
      - USERS=$USERS
      - ADDRESS=ftp.site.domain
    volumes:
      - $VOLUME:/tmp
