version: '3'
services:
  androidstudio:
    image: kelvinlawson/android-studio
#    build:
#      context: .
#      dockerfile: Dockerfile
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
#    - DISPLAY=$DISPLAY
#    - DISPLAY=:0
    - DISPLAY=
#    entrypoint: [ "export", "DISPLAY=" ]
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    volumes:
    - ${datafolder}:/data
     - /tmp/.X11-unix:/tmp/.X11-unix
