services:
    semaphore:
        ports:
            - 3000:3000
        image: public.ecr.aws/semaphore/pro/server:v2.16.51
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: ${PASS}
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
